### PR TITLE
Add arrow option

### PR DESCRIPTION
**Pull request by Atmos4**
Add the option to pass an `arrow` element that will get positioned so that:
- it is always on the edge of the `popper` element 
- it points towards the center of the `reference` element

Here is an example of the arrow's CSS:
```css
.arrow {
  position: fixed;
  /* the rest is just so that it looks like an arrow */
  background-color: inherit;
  width: 10px;
  height: 10px;
  z-index: -1;
  transform: translate(-50%, -50%) rotate(45deg);
}
```

### CODE REVIEW

**Comment by Simonwep** [comment]
Hey! That's really cool :) Could you add a few snapshot tests for that?

**Comment by Atmos4** [comment]
Ran your workflow on my fork: https://github.com/Atmos4/nanopop/actions/runs/3974649283.

**Comment by Simonwep** [comment]
Awesome! Could you update the README as well? I'll merge it than and release a new version shortly after 🥳

**Review by Simonwep — APPROVED** [review]

**Comment by Simonwep** [comment]
Very nice feature, approved and merged :) I'll release a new minor version for this! Thank you ^^

**Pull request merged**
